//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Harmonia.Net5.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SettingsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Harmonia.Net5.Properties.SettingsResources", typeof(SettingsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select _folder.
        /// </summary>
        public static string btnSelectFolder {
            get {
                return ResourceManager.GetString("btnSelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select _executable.
        /// </summary>
        public static string btnSelectMp3GainFolder {
            get {
                return ResourceManager.GetString("btnSelectMp3GainFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP3GAIN EXECUTABLE LOCATION.
        /// </summary>
        public static string MP3Gain_ExecutableLocation {
            get {
                return ResourceManager.GetString("MP3Gain_ExecutableLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP3Gain is used to normalize audio. It cannot be found at the location currently set. Would you like to download/install MP3Gain?.
        /// </summary>
        public static string Mp3GainHelp_MissingExecutable {
            get {
                return ResourceManager.GetString("Mp3GainHelp_MissingExecutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please set the correct path to the MP3Gain.exe file. Otherwise, audio will not be normalized..
        /// </summary>
        public static string Mp3GainHelp_SetValidPath {
            get {
                return ResourceManager.GetString("Mp3GainHelp_SetValidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP3Gain Help.
        /// </summary>
        public static string Mp3GainHelp_Title {
            get {
                return ResourceManager.GetString("Mp3GainHelp_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mp3Gain is used to normalize audio..
        /// </summary>
        public static string Mp3GainHelp_ValidPath {
            get {
                return ResourceManager.GetString("Mp3GainHelp_ValidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output directory.
        /// </summary>
        public static string OutputDirectory {
            get {
                return ResourceManager.GetString("OutputDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Theme and color scheme.
        /// </summary>
        public static string ThemeAndColorScheme {
            get {
                return ResourceManager.GetString("ThemeAndColorScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Window_Title {
            get {
                return ResourceManager.GetString("Window_Title", resourceCulture);
            }
        }
    }
}
